common:
  logger: debug
conn:
  host: localhost
  port: :8080
database:
  host: segment-data
  port: 5432
  username: user
  password: pswd
  name: segment-data
  settings: ?pool_max_conns=10
  migrationPath: ./migration/000001_init_mg.up.sql
