version: '3.8'

services:
  segment-service:
    image: ghcr.io/dupreehkuda/segment-service-prod:latest
    command: -c ./configs/config.prod.yml
    container_name: segment-service
    ports:
      - '80:80'
    restart: always
    volumes:
      - ./reports:/build/reports
    depends_on:
      segment-data:
        condition: service_started

  segment-data:
    image: postgres:latest
    container_name: segment-data
    restart: on-failure
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'