openapi: 3.0.3
info:
  title: Avito Segments Service
  description: |-
    Avito Test Assignment
  version: 1.0.0
  contact:
    name: Danila Kurach
    email: danyakurach@gmail.com
servers:
  - url: 'http://localhost:8080/api/v1'
    description: local
  - url: 'http://1145267-cv99614.tw1.ru/api/v1'
    description: production
tags:
  - name: segment
    description: Operations about segment
  - name: user
    description: Operations about user
paths:
  /segment:
    post:
      tags:
        - segment
      summary: Add new segment
      description: Add new segment
      requestBody:
        $ref: '#/components/requestBodies/SegmentAddRequest'
      responses:
        '200':
          description: Segment exists
        '201':
          description: Segment created
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - segment
      summary: Delete segment
      description: Deletes existing segment
      requestBody:
        $ref: '#/components/requestBodies/SegmentDeleteRequest'
      responses:
        '200':
          description: Segment deleted
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '410':
          $ref: '#/components/responses/GoneError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /user:
    get:
      tags:
        - user
      summary: Get user's active segments
      description: Get user's active segments
      requestBody:
        $ref: '#/components/requestBodies/UserSegmentsRequest'
      responses:
        '200':
          $ref: '#/components/responses/UsersSegmentsResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - user
      summary: Add segments to user
      description: Add segments to user
      requestBody:
        $ref: '#/components/requestBodies/UserSegmentsRequest'
      responses:
        '200':
          description: Segments added
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - user
      summary: Delete segments from user
      description: Delete segments from user
      requestBody:
        description: Delete segments from user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Segments deleted
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    Segment:
      required:
        - tag
      type: object
      properties:
        tag:
          type: string
          example: AVITO_VOICE_MESSAGES
        description:
          type: string
          example: Feature flag for voice messages
    User:
      required:
        - id
      type: object
      properties:
        id:
          type: string
          example: 0c496832-37a4-11ee-8bf7-0242c0a80002
        segments:
          type: array
          items:
            type: string
          example: [AVITO_VOICE_MESSAGES, AVITO_DISCOUNT_30]
    Error:
      title: Error
      type: object
      description: Error type which is returned on a failed request
      properties:
        message:
          type: string
      required:
        - message
  requestBodies:
    SegmentAddRequest:
      description: Segment addition
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Segment'
    SegmentDeleteRequest:
      description: Segment deletion
      content:
        application/json:
          schema:
            required:
              - tag
            type: object
            properties:
              tag:
                type: string
                example: AVITO_VOICE_MESSAGES
    UserSegmentsRequest:
      description: Retrieving user's active segments
      content:
        application/json:
          schema:
            required:
              - id
            type: object
            properties:
              id:
                type: string
                example: 0c496832-37a4-11ee-8bf7-0242c0a80002
              segments:
                type: array
                items:
                  type: object
                  required:
                    - tag
                  properties:
                    tag:
                      type: string
                      example: AVITO_VOICE_MESSAGES
                    expire:
                      type: string
                      example: 2006-01-02T15:04:05Z07:00
                      description: RFC3339 required
    UserAddSegmentsRequest:
      description: Add segments to user
      content:
        application/json:
          schema:
            required:
              - id
            type: object
            properties:
              id:
                type: string
                example: 0c496832-37a4-11ee-8bf7-0242c0a80002
    UserRequest:
      description: Segment addition/deletion on user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
  responses:
    UsersSegmentsResponse:
      description: Get Users Segments
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            example:
              value:
                message: Internal Server Error
    NotFoundError:
      description: Not Found Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            example:
              value:
                message: Not found
    BadRequestError:
      description: Bad Request Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            example:
              value:
                message: Bad Request
    GoneError:
      description: Gone Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            example:
              value:
                message: Segment has been deleted