name: build

on:
  workflow_run:
    workflows: [test]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: docker_buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push segment-service image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/segment-service-prod:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/segment-service-prod:latest
