name: Test

on:
  push:
    branches:
      - main
    paths:
      - cmd/**
      - internal/**
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: make test
